import { realpath } from "node:fs/promises";
import { z } from "zod";
import { evaluateEndpoint } from "../runtime";

// Structural types keep loading a local plugin independent of an SDK dependency.
type OpenCodeContext = {
  directory: string;
  client: {
    session: {
      get(input: {
        path: { id: string };
        query: { directory: string };
        signal: AbortSignal;
      }): Promise<unknown>;
    };
  };
};

const sessionId = z.string().min(1).max(256);
const messageSchema = z.object({
  message: z.object({ role: z.literal("user"), sessionID: sessionId }),
  parts: z.array(
    z.object({
      type: z.string(),
      text: z.string().optional(),
      synthetic: z.boolean().optional(),
      ignored: z.boolean().optional(),
    }),
  ),
});
const sessionSchema = z.object({
  data: z.object({
    id: sessionId,
    directory: z.string(),
    parentID: z.string().optional(),
  }),
});

// Export only the plugin: OpenCode may invoke every function export as a plugin.
export default async function turnstileOpenCode(context: OpenCodeContext) {
  const root = await realpath(context.directory);
  const goals = new Map<string, { goal: string; updatedAt: number }>();
  const pending = new Map<string, object>();
  return {
    "chat.message": async (input: { sessionID: string }, output: unknown) => {
      const id = sessionId.parse(input.sessionID);
      // Clear old intent before asynchronous validation. A parallel tool must never
      // inherit the previous prompt while the replacement is being checked.
      goals.delete(id);
      const generation = {};
      pending.set(id, generation);
      try {
        const parsed = messageSchema.parse(output);
        if (parsed.message.sessionID !== id) return;
        const goal = parsed.parts
          .filter((part) => part.type === "text" && !part.synthetic && !part.ignored)
          .map((part) => part.text ?? "")
          .join("\n");
        if (!goal.trim() || goal.length > 16000) return;
        const result = sessionSchema.parse(
          await context.client.session.get({
            path: { id },
            query: { directory: context.directory },
            signal: AbortSignal.timeout(4000),
          }),
        );
        // Subagent prompts can be generated by the model. They are not user intent.
        if (result.data.id !== id || result.data.parentID !== undefined) return;
        if ((await realpath(result.data.directory)) !== root) return;
        if (pending.get(id) !== generation) return;
        goals.set(id, { goal, updatedAt: Date.now() });
      } catch {
        // Missing or unverifiable intent becomes review through the shared guard.
      } finally {
        if (pending.get(id) === generation) pending.delete(id);
      }
    },
    "tool.execute.before": async (
      input: { tool: string; sessionID: string; callID: string },
      output: { args: unknown },
    ) => {
      const id = sessionId.parse(input.sessionID);
      const saved = goals.get(id);
      const age = saved ? Date.now() - saved.updatedAt : -1;
      const goal = saved && age >= 0 && age <= 86400000 ? saved.goal : "";
      const args = z.record(z.string(), z.unknown()).parse(output.args);
      const snapshot = JSON.stringify(args);
      const decision = await evaluateEndpoint({
        harness: "opencode",
        sessionId: id,
        cwd: context.directory,
        userGoal: goal,
        tool: input.tool,
        arguments: args,
      });
      // The result belongs to the intent captured before the asynchronous check.
      // A replacement prompt, session deletion, or disposal invalidates it.
      if (goals.get(id) !== saved)
        throw new Error("Turnstile: task intent changed during evaluation; check the action again");
      if (JSON.stringify(output.args) !== snapshot)
        throw new Error("Turnstile: tool arguments changed during evaluation");
      if (decision.enforced) {
        // The before-tool hook has no native approval callback. Throwing stops
        // both denials and reviews without weakening OpenCode permissions.
        throw new Error(
          `Turnstile: ${decision.verdict}. ${decision.reasons.join(", ")}. Decision ${decision.id}`,
        );
      }
    },
    event: async ({ event }: { event: { type: string; properties?: unknown } }) => {
      if (event.type !== "session.deleted") return;
      const parsed = z.object({ info: z.object({ id: sessionId }) }).safeParse(event.properties);
      if (parsed.success) {
        goals.delete(parsed.data.info.id);
        pending.delete(parsed.data.info.id);
      }
    },
    dispose: async () => {
      goals.clear();
      pending.clear();
    },
  };
}
